# Generated by Django 5.0.6 on 2024-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teclado_conectividad_alter_teclado_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teclado',
            name='conectividad',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='formato',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='keycaps',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='switch',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='teclado',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
